/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Event, Client, Vendor } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Apex Global Tech',
    email: 'events@apexglobal.com',
    phone: '555-0123',
    company: 'Apex Global Industries',
    segment: 'Enterprise',
    totalSpend: 112000,
    eventCount: 3,
    firstEventDate: '2026-01-15',
    lastEventDate: '2026-05-18',
    lifetimeValue: 150000,
    retentionRisk: 'Low',
    notes: 'Key account. Prefers luxury corporate packages. Prompt payer.'
  },
  {
    id: 'c2',
    name: 'Sarah & Michael Wedding',
    email: 'sarah.michael@gmail.com',
    phone: '555-0199',
    segment: 'Individual',
    totalSpend: 45000,
    eventCount: 1,
    firstEventDate: '2026-06-12',
    lastEventDate: '2026-06-12',
    lifetimeValue: 45000,
    retentionRisk: 'Low',
    notes: 'Delighted with the venue setup and catering. Recommended us to friends.'
  },
  {
    id: 'c3',
    name: 'Greenwood Education Foundation',
    email: 'contact@greenwoodfoundation.org',
    phone: '555-0144',
    segment: 'SMB',
    totalSpend: 18000,
    eventCount: 1,
    firstEventDate: '2026-03-22',
    lastEventDate: '2026-03-22',
    lifetimeValue: 35000,
    retentionRisk: 'Medium',
    notes: 'Nonprofit client. Highly budget-conscious. Demanded several discount rounds.'
  },
  {
    id: 'c4',
    name: 'Starlight Retailers',
    email: 'marketing@starlightretail.com',
    phone: '555-0188',
    company: 'Starlight Group',
    segment: 'SMB',
    totalSpend: 52000,
    eventCount: 2,
    firstEventDate: '2026-02-10',
    lastEventDate: '2026-06-25',
    lifetimeValue: 80000,
    retentionRisk: 'Low',
    notes: 'Responsive marketing team. Interested in quarterly product launch events.'
  },
  {
    id: 'c5',
    name: 'David Miller Private Event',
    email: 'dmiller@yahoo.com',
    phone: '555-0167',
    segment: 'Individual',
    totalSpend: 12500,
    eventCount: 1,
    firstEventDate: '2026-04-05',
    lastEventDate: '2026-04-05',
    lifetimeValue: 12500,
    retentionRisk: 'High',
    notes: 'Complained about florists. Unlikely to book another private party.'
  },
  {
    id: 'c6',
    name: 'Vanguard Capital',
    email: 'operations@vanguardcap.com',
    phone: '555-0111',
    company: 'Vanguard Capital Partners',
    segment: 'Enterprise',
    totalSpend: 84000,
    eventCount: 2,
    firstEventDate: '2026-02-28',
    lastEventDate: '2026-06-28',
    lifetimeValue: 120000,
    retentionRisk: 'Low',
    notes: 'Hosts high-end partner retreats and VIP dinners. Demands top-tier AV and safety.'
  },
  {
    id: 'c7',
    name: 'BioHealth Labs',
    email: 'hr@biohealthlabs.org',
    phone: '555-0155',
    company: 'BioHealth Labs Inc.',
    segment: 'Enterprise',
    totalSpend: 31000,
    eventCount: 1,
    firstEventDate: '2026-05-10',
    lastEventDate: '2026-05-10',
    lifetimeValue: 60000,
    retentionRisk: 'Medium',
    notes: 'Spring health symposium. Had scheduling conflicts with their catering requirements.'
  },
  {
    id: 'c8',
    name: 'Olivia & Liam Anniversary',
    email: 'olivia.l@outlook.com',
    phone: '555-0122',
    segment: 'Individual',
    totalSpend: 9500,
    eventCount: 1,
    firstEventDate: '2026-01-22',
    lastEventDate: '2026-01-22',
    lifetimeValue: 9500,
    retentionRisk: 'Low',
    notes: 'Small gathering, highly satisfied with security and catering coordination.'
  },
  {
    id: 'c9',
    name: 'EcoAction Alliance',
    email: 'gogreen@ecoaction.org',
    phone: '555-0177',
    segment: 'SMB',
    totalSpend: 15000,
    eventCount: 1,
    firstEventDate: '2026-04-18',
    lastEventDate: '2026-04-18',
    lifetimeValue: 25000,
    retentionRisk: 'Medium',
    notes: 'Advocacy group. Prefers local, eco-friendly vendors. Strict zero-waste policy.'
  },
  {
    id: 'c10',
    name: 'Pinnacle Sports Group',
    email: 'info@pinnaclesports.com',
    phone: '555-0138',
    company: 'Pinnacle Holding Ltd.',
    segment: 'SMB',
    totalSpend: 41000,
    eventCount: 2,
    firstEventDate: '2026-03-08',
    lastEventDate: '2026-06-18',
    lifetimeValue: 75000,
    retentionRisk: 'Low',
    notes: 'Annual awards banquet and dynamic team-building games. Solid account.'
  },
  {
    id: 'c11',
    name: 'Sophia Baker Quinceañera',
    email: 'baker.family@hotmail.com',
    phone: '555-0182',
    segment: 'Individual',
    totalSpend: 28000,
    eventCount: 1,
    firstEventDate: '2026-05-24',
    lastEventDate: '2026-05-24',
    lifetimeValue: 28000,
    retentionRisk: 'Low',
    notes: 'Beautiful 15th birthday celebration. Highly interactive entertainment requested.'
  },
  {
    id: 'c12',
    name: 'Cascade Healthcare Corp',
    email: 'community@cascadehealth.com',
    phone: '555-0100',
    company: 'Cascade Medical Group',
    segment: 'Enterprise',
    totalSpend: 73000,
    eventCount: 2,
    firstEventDate: '2026-03-15',
    lastEventDate: '2026-06-30',
    lifetimeValue: 140000,
    retentionRisk: 'High',
    notes: 'Frequent medical conferences. Complained about AV delays on the recent June event.'
  }
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'v1',
    name: 'Gourmet Delights Catering',
    category: 'Catering',
    totalContracts: 9,
    onTimeRate: 95,
    avgCostVariance: 2.1,
    reliabilityScore: 94,
    totalPaid: 95000,
    flagged: false,
    notes: 'Premium menus, professional staff. Excellent presentation and custom menus.'
  },
  {
    id: 'v2',
    name: 'ProSonic AV Solutions',
    category: 'AV',
    totalContracts: 8,
    onTimeRate: 75,
    avgCostVariance: 8.5,
    reliabilityScore: 68,
    totalPaid: 64000,
    flagged: true,
    notes: 'Frequent tardiness during soundchecks. Cost variance is high due to last-minute gear additions.'
  },
  {
    id: 'v3',
    name: 'Shutter & Light Studios',
    category: 'Photography',
    totalContracts: 6,
    onTimeRate: 100,
    avgCostVariance: 0.0,
    reliabilityScore: 98,
    totalPaid: 32000,
    flagged: false,
    notes: 'Extremely reliable. Delivers high-quality digital photos ahead of schedule.'
  },
  {
    id: 'v4',
    name: 'The Grand Ballroom & Plaza',
    category: 'Venue',
    totalContracts: 5,
    onTimeRate: 98,
    avgCostVariance: -1.2,
    reliabilityScore: 96,
    totalPaid: 145000,
    flagged: false,
    notes: 'Our primary high-end partner. Elegant design, flawless operations, strict guidelines.'
  },
  {
    id: 'v5',
    name: 'Blooms & Bows Florals',
    category: 'Florist',
    totalContracts: 7,
    onTimeRate: 88,
    avgCostVariance: 12.4,
    reliabilityScore: 78,
    totalPaid: 21000,
    flagged: false,
    notes: 'Beautiful work, but price fluctuations in seasonal roses led to cost variance.'
  },
  {
    id: 'v6',
    name: 'Apex Safety & Security',
    category: 'Security',
    totalContracts: 11,
    onTimeRate: 100,
    avgCostVariance: 1.0,
    reliabilityScore: 99,
    totalPaid: 28500,
    flagged: false,
    notes: 'Excellent, unobtrusive personnel. Highly recommended for celebrity/high-end corporate events.'
  },
  {
    id: 'v7',
    name: 'Artisan Culinary Group',
    category: 'Catering',
    totalContracts: 5,
    onTimeRate: 80,
    avgCostVariance: 14.8,
    reliabilityScore: 72,
    totalPaid: 48000,
    flagged: false,
    notes: 'Amazing organic farm-to-table menus. Prone to minor logistic delays.'
  },
  {
    id: 'v8',
    name: 'Matrix Lights & Laser Tech',
    category: 'AV',
    totalContracts: 4,
    onTimeRate: 90,
    avgCostVariance: 3.2,
    reliabilityScore: 89,
    totalPaid: 38000,
    flagged: false,
    notes: 'Great ambient lighting and laser packages. Excellent high-energy team.'
  },
  {
    id: 'v9',
    name: 'Mirage Tent & Rentals',
    category: 'Other',
    totalContracts: 4,
    onTimeRate: 50,
    avgCostVariance: 18.5,
    reliabilityScore: 48,
    totalPaid: 29000,
    flagged: true,
    notes: 'Severely short-staffed. Arrived 4 hours late to setup Apex Corporate retreat, almost ruining it.'
  },
  {
    id: 'v10',
    name: 'Luxe Valet Services',
    category: 'Other',
    totalContracts: 5,
    onTimeRate: 96,
    avgCostVariance: 0.5,
    reliabilityScore: 95,
    totalPaid: 14000,
    flagged: false,
    notes: 'Highly polished valet drivers. Very smooth coordination with city parking authorities.'
  }
];

export const INITIAL_EVENTS: Event[] = [
  // January 2026
  {
    id: 'e1',
    name: 'Apex Winter Strategy Summit',
    type: 'Corporate',
    date: '2026-01-15',
    revenue: 42000,
    costs: 28000,
    profit: 14000,
    clientId: 'c1',
    vendorIds: ['v1', 'v2', 'v4', 'v6'],
    status: 'Completed',
    guestCount: 150,
    venue: 'The Grand Ballroom & Plaza'
  },
  {
    id: 'e2',
    name: 'Olivia & Liam 25th Anniversary',
    type: 'Private',
    date: '2026-01-22',
    revenue: 9500,
    costs: 6500,
    profit: 3000,
    clientId: 'c8',
    vendorIds: ['v7', 'v5', 'v10'],
    status: 'Completed',
    guestCount: 60,
    venue: 'Downtown Garden Gallery'
  },
  // February 2026
  {
    id: 'e3',
    name: 'Starlight Retailers Spring Launch',
    type: 'Corporate',
    date: '2026-02-10',
    revenue: 27000,
    costs: 19000,
    profit: 8000,
    clientId: 'c4',
    vendorIds: ['v1', 'v8', 'v10'],
    status: 'Completed',
    guestCount: 120,
    venue: 'Modern Arts Pavilion'
  },
  {
    id: 'e4',
    name: 'Vanguard Capital Partners Dinner',
    type: 'Corporate',
    date: '2026-02-28',
    revenue: 34000,
    costs: 22000,
    profit: 12000,
    clientId: 'c6',
    vendorIds: ['v1', 'v2', 'v6', 'v10'],
    status: 'Completed',
    guestCount: 80,
    venue: 'Skyline Penthouse Club'
  },
  // March 2026
  {
    id: 'e5',
    name: 'Pinnacle Sports Spring Kickoff',
    type: 'Corporate',
    date: '2026-03-08',
    revenue: 16000,
    costs: 11500,
    profit: 4500,
    clientId: 'c10',
    vendorIds: ['v7', 'v8', 'v6'],
    status: 'Completed',
    guestCount: 110,
    venue: 'Eastside Athletic Club'
  },
  {
    id: 'e6',
    name: 'Cascade Medical Annual Symposium',
    type: 'Corporate',
    date: '2026-03-15',
    revenue: 48000,
    costs: 34500,
    profit: 13500,
    clientId: 'c12',
    vendorIds: ['v1', 'v2', 'v4', 'v6'],
    status: 'Completed',
    guestCount: 220,
    venue: 'The Grand Ballroom & Plaza'
  },
  {
    id: 'e7',
    name: 'Greenwood Gala for Education',
    type: 'Nonprofit',
    date: '2026-03-22',
    revenue: 18000,
    costs: 13200,
    profit: 4800,
    clientId: 'c3',
    vendorIds: ['v7', 'v2', 'v5', 'v6'],
    status: 'Completed',
    guestCount: 180,
    venue: 'Community Heritage Hall'
  },
  // April 2026
  {
    id: 'e8',
    name: 'David Miller 40th Birthday Bash',
    type: 'Private',
    date: '2026-04-05',
    revenue: 12500,
    costs: 8200,
    profit: 4300,
    clientId: 'c5',
    vendorIds: ['v1', 'v5', 'v8'],
    status: 'Completed',
    guestCount: 75,
    venue: 'Whiskey Barrels Warehouse'
  },
  {
    id: 'e9',
    name: 'EcoAction Alliance Annual Luncheon',
    type: 'Nonprofit',
    date: '2026-04-18',
    revenue: 15000,
    costs: 10800,
    profit: 4200,
    clientId: 'c9',
    vendorIds: ['v7', 'v5', 'v6'],
    status: 'Completed',
    guestCount: 140,
    venue: 'Eco-Greenhouse Conservatory'
  },
  // May 2026
  {
    id: 'e10',
    name: 'BioHealth Labs Spring Colloquium',
    type: 'Corporate',
    date: '2026-05-10',
    revenue: 31000,
    costs: 21500,
    profit: 9500,
    clientId: 'c7',
    vendorIds: ['v1', 'v2', 'v6'],
    status: 'Completed',
    guestCount: 130,
    venue: 'BioTech Innovation Center'
  },
  {
    id: 'e11',
    name: 'Apex Global Product Showcase',
    type: 'Corporate',
    date: '2026-05-18',
    revenue: 55000,
    costs: 38000,
    profit: 17000,
    clientId: 'c1',
    vendorIds: ['v1', 'v2', 'v4', 'v6', 'v10'],
    status: 'Completed',
    guestCount: 250,
    venue: 'The Grand Ballroom & Plaza'
  },
  {
    id: 'e12',
    name: 'Sophia Baker Sweet 15',
    type: 'Private',
    date: '2026-05-24',
    revenue: 28000,
    costs: 19500,
    profit: 8500,
    clientId: 'c11',
    vendorIds: ['v1', 'v5', 'v8', 'v10'],
    status: 'Completed',
    guestCount: 160,
    venue: 'Elegance Palace Ballroom'
  },
  // June 2026
  {
    id: 'e13',
    name: 'Sarah & Michael Elegant Wedding',
    type: 'Wedding',
    date: '2026-06-12',
    revenue: 45000,
    costs: 31000,
    profit: 14000,
    clientId: 'c2',
    vendorIds: ['v1', 'v3', 'v4', 'v5', 'v6', 'v10'],
    status: 'Completed',
    guestCount: 200,
    venue: 'The Grand Ballroom & Plaza'
  },
  {
    id: 'e14',
    name: 'Pinnacle Corporate Retreat & AV Show',
    type: 'Corporate',
    date: '2026-06-18',
    revenue: 25000,
    costs: 17500,
    profit: 7500,
    clientId: 'c10',
    vendorIds: ['v7', 'v2', 'v6', 'v9'],
    status: 'Completed',
    guestCount: 90,
    venue: 'Lakeside Resort Lodges'
  },
  {
    id: 'e15',
    name: 'Starlight Retail Summer Carnival',
    type: 'Corporate',
    date: '2026-06-25',
    revenue: 25000,
    costs: 20500,
    profit: 4500,
    clientId: 'c4',
    vendorIds: ['v1', 'v6', 'v9', 'v10'],
    status: 'Completed',
    guestCount: 400,
    venue: 'Starlight Retailers Plaza'
  },
  {
    id: 'e16',
    name: 'Vanguard Capital Executive Retreat',
    type: 'Corporate',
    date: '2026-06-28',
    revenue: 50000,
    costs: 32000,
    profit: 18000,
    clientId: 'c6',
    vendorIds: ['v1', 'v3', 'v4', 'v6', 'v10'],
    status: 'Upcoming',
    guestCount: 50,
    venue: 'The Grand Ballroom & Plaza'
  },
  {
    id: 'e17',
    name: 'Cascade Health Partners VIP Banquet',
    type: 'Corporate',
    date: '2026-06-30',
    revenue: 25000,
    costs: 18000,
    profit: 7000,
    clientId: 'c12',
    vendorIds: ['v1', 'v2', 'v6', 'v10'],
    status: 'Upcoming',
    guestCount: 90,
    venue: 'Cascade Executive Lounge'
  },
  {
    id: 'e18',
    name: 'Apex Global Mid-Year Celebration',
    type: 'Corporate',
    date: '2026-06-15',
    revenue: 15000,
    costs: 11000,
    profit: 4000,
    clientId: 'c1',
    vendorIds: ['v1', 'v2', 'v6'],
    status: 'Cancelled',
    guestCount: 120,
    venue: 'Apex Office Terraces'
  }
];
